#!/usr/bin/env sh

# bar settings
yabai -m config status_bar off
yabai -m config status_bar_text_font "DroidSansM Nerd Font:Bold:12.0"
yabai -m config status_bar_icon_font "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color 0xff202020
yabai -m config status_bar_foreground_color 0xffa8a8a8
yabai -m config status_bar_space_icon_strip I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip  
yabai -m config status_bar_space_icon 
yabai -m config status_bar_clock_icon 
# yabai -m config window_animation_duration   1.0

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow float
yabai -m config window_border off
yabai -m config window_border_placement inset
yabai -m config window_border_width 4
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff505050
yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config window_topmost off

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 8

# Float Windows
yabai -m rule --add title='Preferences' manage=off layer=above
yabai -m rule --add title='^(Opening)' manage=off layer=above
yabai -m rule --add title='Library' manage=off layer=above
yabai -m rule --add app='^System Preferences$' manage=off layer=above
yabai -m rule --add app='Activity Monitor' manage=off layer=above
yabai -m rule --add app='Finder' manage=off layer=above
yabai -m rule --add app='^System Information$' manage=off layer=above

echo "yabai configuration loaded.."
